#!/bin/bash

set -eu

echo "deploy-testflight"

cf login -a ${CF_API_URL} --skip-ssl-validation -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}

cd git
cat <<EOF > cf/manifest.yml
---
applications:
  - name: testflight-config-server-broker
    path: ../
    env:
      CONFIG_SERVER_BROKER_CONFIG: ((config_server_broker_config))
EOF

cat <<EOF > cf/secrets.yml
broker_auth:
  user: admin
  password: admin
cloud_foundry_config:
  api_url: ${CF_API_URL}
  skip_ssl_validation: true
  cf_username: ${CF_USERNAME}
  cf_password: ${CF_PASSWORD}
  uaa_client_id: ${UAA_CLIENT_ID}
  uaa_client_secret: ${UAA_CLIENT_SECRET}
instance_space_guid: ${INSTANCE_SPACE_GUID}
instance_domain: ${INSTANCE_DOMAIN}
EOF

bin/push-broker

cf a
