#!/bin/bash

set -eu

echo "deploy-testflight"

cf login -a ${CF_API_URL} --skip-ssl-validation -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
apt-get install software-properties-common -y
apt-get update -y
add-apt-repository ppa:rmescandon/yq -y
apt update -y
apt install yq -y

pushd git

app_name=testflight-config-server-broker

cat <<EOF > cf/manifest.yml
---
applications:
  - name: ${app_name}
    path: ../
    env:
      CONFIG_SERVER_BROKER_CONFIG: ((config_server_broker_config))
EOF

cat <<EOF > cf/secrets.yml
broker_auth:
  user: admin
  password: admin
config_server_release_tag:  (( file fetch-spring-latest-rel/tag ))
cloud_foundry_config:
  api_url: ${CF_API_URL}
  skip_ssl_validation: true
  cf_username: ${CF_USERNAME}
  cf_password: ${CF_PASSWORD}
  uaa_client_id: ${UAA_CLIENT_ID}
  uaa_client_secret: ${UAA_CLIENT_SECRET}
instance_space_guid: ${INSTANCE_SPACE_GUID}
instance_domain: ${INSTANCE_DOMAIN}
EOF

bin/push-broker

cf a

url="https://$(cf a | grep ${app_name} | awk '{print $NF}')"

cf create-service-broker ${app_name} admin admin ${url} --space-scoped

cf marketplace

cf create-service config-server basic testflight-instance -c '{"gitRepoUrl": "https://github.com/spring-cloud-samples/config-repo"}'
