broker_auth:
  user: (( param "Please override broker_auth.user" ))
  password: (( param "Please override broker_auth.password" ))
service_name: config-server
service_id: config-server
basic_plan_name: basic
basic_plan_id: basic
description: Broker to create config-servers
long_description: Broker to create config-servers
cloud_foundry_config:
  api_url: (( param "Please override cloud_foundry_config.api_url in inputs.yml" ))
  user: (( param "Please override cloud_foundry_config.user in inputs.yml" ))
  password: (( param "Please override cloud_foundry_config.password in inputs.yml" ))
