---
meta:
  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
jobs:
  - name: test
    public: true
    serial: true
    plan:
      - do:
        - { get: git, trigger: true }
        #- task: test
        #  config:
        #    platform: linux
        #    image_resource:
        #      type: docker-image
        #      source:
        #        repository: (( grab meta.image.name ))
        #        tag:        (( grab meta.image.tag ))
        #    inputs:
        #      - name: git
        #        path: (( concat "gopath/src/" meta.go.module ))
        #    run:
        #      path: (( concat "./gopath/src/" meta.go.module "/ci/scripts/test" ))
        #      args: []
        #    params:
        #      MODULE: (( grab meta.go.module ))
        #on_failure:
        #  put: notify
        #  params:
        #    channel:  (( grab meta.slack.channel ))
        #    username: (( grab meta.slack.username ))
        #    icon_url: (( grab meta.slack.icon ))
        #    text:    '(( concat meta.slack.fail_url " " meta.pipeline ": test job failed" ))'
resources:
  - name: git
    type: git
    source:
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch ))
      private_key: (( grab meta.github.private_key ))
