---
meta:

  name:    config-server-broker
  target:  snw 
  url:     pipes.starkandwayne.com

  initial_version: 0.0.1

  git:
    email: ci@starkandwayne.com
    name:  CI Bot

  github:
    owner:  starkandwayne
    repo:   config-server-broker
    branch: initial-pipeline
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  aws:
    access_key:  ((cfcommunity.access))
    secret_key:  ((cfcommunity.secret))
